import "./FileContentModal.scss";

export default function FileContentModal({ fileData }) {
    const modalStyle = {
        position: "absolute",
        top: "15%",
        bottom: "15%",
        left: "15%",
        right: "15%",
        backgroundColor: "#333333",
    };

    const modalBarStyle = {
        display: "flex",
        position: "relative",
        top: "0",
        right: "0",
        width: "20px",
        height: "20px",
        fontSize: "15px",
        backgroundColor: "red",
        justifyContent: "center",
        fontWeight: "bold",
    };

    const modalContentStyle = {
        margin: "20px",
        // width: "100%",
        height: "85%",
        inset: "15%",
        border: "2px solid cyan",
    };

    return (
        // <div style={modalStyle}>{e.currentTarget.dataset.filecontent}</div>
        // <div style={modalStyle}>{fileData.fileContent}</div>
        <div
            className="fileModal"
            // style={modalStyle}
        >
            <div
                className="fileModal-bar"
                // style={modalBarStyle}
                onClick={(e) => {
                    console.log(e.currentTarget);
                }}
            >
                X
            </div>
            <div
                className="fileModal-content"
                // style={modalContentStyle}
            >
                {fileData !== "none" ? (
                    <>
                        <label>
                            {/* File name */}
                            {fileData.fileName}
                            <input />
                        </label>
                        <label>
                            {/* File Type */}
                            {fileData.fileName}
                            <input />
                        </label>
                        <label>
                            {/* Content */}
                            {fileData.fileContent}
                            <input />
                        </label>
                    </>
                ) : (
                    <>
                    <p>
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                        No file open
                    </p>
                    </>
                )}
            </div>
        </div>
    );
}
